[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "scrappy"
version = "0.2.0"
requires-python = ">=3.8"
authors = [
    {name = "Lexy Andati", email = "landati@duck.com"}
]
description = "Generate polarimetric spectra on independent lines of sight across a source"
readme = "README.rst"
license = "MIT"
license-files = ["LICENSE"]


dependencies = [ 
    "astropy",
    "bokeh==2.4.3",
    "regions",
    "numpy",
    "matplotlib",
    "natsort",
    "scipy"
]

classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Astronomy"
]


[project.scripts]
sc-los = "scrap.scrappy:console"
sc-losrm = "rmsynthesis.rm_synthesis:console"
sc-rmmap = "scrappy.rmsynthesis.rmmap_x2:console"
sc-bokehplot = "bkplots.plot_bk:console"
sc-ifit = "imageops.new_fit:console"
sc-beam-plot = "imageops.plot_bmaj_bmin:console"
sc-houdini = "imageops.simple_mask:console"
scrappy = "main:console"
sc-depol = "rmsynthesis.rmmap_x2:depol_shim"



[project.urls]
Repository = "https://github.com/Mulan-94/scrappy.git"
Documentation = "https://mulan-94.github.io/scrappy/"
Issues = "https://github.com/Mulan-94/scrappy"



[options]
packages = [
    "bkplots",
    "imageops",
    "rmsynthesis",
    "scrap",
    "utils"
]



[project.optional-dependencies]
casa = ["casatasks"]


[tool.setuptools]
package-dir = {"scrappy" = "src/scrappy"}
#packages = [
    #"scrappy",
    #"bkplots",
    #"imageops",
    #"rmsynthesis",
    #"scrap",
    #"utils"
#]

[tool.setuptools.packages.find]
where = ["src"]


[tool.black]
line-length = 82
target-version = ['py37']

